apiVersion: v1
kind: Service
metadata:
  name: glpi
  namespace: glpi
  labels:
    app: glpi
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: glpi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glpi
  namespace: glpi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glpi
  template:
    metadata:
      labels:
        app: glpi
    spec:
      containers:
        - name: glpi
          image: glpi/glpi:latest   # GLPI Docker image
          ports:
            - containerPort: 80
              name: http
          env:
            - name: MARIADB_HOST
              value: mariadb.glpi.svc.cluster.local
            - name: MARIADB_PORT
              value: "3306"
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-database
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-user
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-password
