# GLPI Service
apiVersion: v1
kind: Service
metadata:
  name: glpi
  namespace: glpi
  labels:
    app: glpi
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      name: http
  selector:
    app: glpi
