apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: glpi
spec:
  serviceName: glpi
  replicas: 1
  selector:
    matchLabels:
      app: glpi
  template:
    metadata:
      labels:
        app: glpi
    spec:
      securityContext:        # <-- pod-level securityContext
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 33
      containers:
      - name: glpi
        image: glpi/glpi:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: glpi-files
          mountPath: /var/glpi/files
        - name: glpi-config
          mountPath: /var/glpi/config
  volumeClaimTemplates:
  - metadata:
      name: glpi-files
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
  - metadata:
      name: glpi-config
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 3Gi
