# GLPI StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: glpi
  namespace: glpi
spec:
  serviceName: glpi
  replicas: 1
  selector:
    matchLabels:
      app: glpi
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
  template:
    metadata:
      labels:
        app: glpi
    spec:
      containers:
        - name: glpi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          env:
            - name: MARIADB_HOST
              value: mariadb.glpi.svc.cluster.local
            - name: MARIADB_PORT
              value: "3306"
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-database
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-user
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-password
          volumeMounts:
            - name: glpi-data
              mountPath: /var/www/html
  volumeClaimTemplates:
    - metadata:
        name: glpi-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        storageClassName: {{ .Values.persistence.storageClass }}
