apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: glpi
  namespace: "{{ .Release.Namespace }}"
spec:
  serviceName: glpi
  replicas: 1
  selector:
    matchLabels:
      app: glpi
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
  template:
    metadata:
      labels:
        app: glpi
    spec:
      securityContext:
        runAsUser: 33        # main container runs as www-data
        runAsGroup: 33
        fsGroup: 33
      initContainers:
      - name: fix-perms
        image: busybox
        securityContext:
          runAsUser: 0       # run initContainer as root
        command: ["sh", "-c", "chown -R 33:33 /var/glpi/files /var/glpi/config /var/glpi/marketplace /var/glpi/logs"]
        volumeMounts:
        - name: glpi-files
          mountPath: /var/glpi/files
        - name: glpi-config
          mountPath: /var/glpi/config
        - name: glpi-marketplace
          mountPath: /var/glpi/marketplace
        - name: glpi-logs
          mountPath: /var/glpi/logs
      containers:
      - name: glpi
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
        - containerPort: 80
          name: http
        env:
        - name: MARIADB_HOST
          value: mariadb.{{ .Release.Namespace }}.svc.cluster.local
        - name: MARIADB_PORT
          value: "3306"
        - name: MARIADB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-database
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-user
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-password
        volumeMounts:
        - name: glpi-files
          mountPath: /var/glpi/files
        - name: glpi-config
          mountPath: /var/glpi/config
        - name: glpi-marketplace
          mountPath: /var/glpi/marketplace
  volumeClaimTemplates:
  - metadata:
      name: glpi-files
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
      storageClassName: glpi-retain
  - metadata:
      name: glpi-config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: glpi-retain
  - metadata:
      name: glpi-marketplace
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: glpi-retain
