apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: {{ .Release.Namespace }}
  labels:
    app: mariadb
spec:
  clusterIP: None
  ports:
    - port: 3306
      name: mysql
  selector:
    app: mariadb
